# NumPy Arithmetic and Statistics

In [5]:
import numpy as np
#Universal function and method
#reduce and accumulate
x=np.arange(10)
sum_all=np.add.reduce(x)
print(x)
print(sum_all)
#applying for n dimensional array
y=np.arange(16).reshape((4,4))
sum_y=np.add.reduce(y)
print("Grid y=",y)
print("Sum of y=",sum_y)

[0 1 2 3 4 5 6 7 8 9]
45
Grid y= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum of y= [24 28 32 36]


In [7]:
#applying accumulate functions 
s=np.arange(12)
sum_acc=np.add.accumulate(s)
print(s)
print(sum_acc)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [9]:
#Aggregation
s=np.arange(14).reshape((2,7))
print("Sum_of_s=",np.sum(x))
print("Mean_of_s",np.mean(x))
print("Max_of_s",np.max(x))
print("Min_of_s",np.min(x))
#applying it to the 2d array
x=np.arange(16).reshape((4,4))
print(x)
print("Sum_x=",x.sum())
print("Mean_x=",x.mean())
print("Min_X=",x.min())
print("Max_x",x.max())

Sum_of_s= 45
Mean_of_s 4.5
Max_of_s 9
Min_of_s 0
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum_x= 120
Mean_x= 7.5
Min_X= 0
Max_x 15


In [12]:
#Comparison and boolean mask
x=np.arange(16)
#comparison operator always return boolean values
print(x>4)
print(x<=10)
print(x*2==x**2)
#numpy also gives us many other operations like count_nonzero,all,any etc
print(np.count_nonzero(x>7))
print(np.all(x<5))
print(np.any(x>=6))
#using boolean mask
grid=np.random.randint(1,14,(3,3))
print(grid)
#applying boolean operation
print(x<6)
#applying boolean mask
print(x[x<6])

[False False False False False  True  True  True  True  True  True  True
  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True False
 False False False False]
[ True False  True False False False False False False False False False
 False False False False]
8
False
True
[[11  5 13]
 [ 7  5 13]
 [ 9  7  4]]
[ True  True  True  True  True  True False False False False False False
 False False False False]
[0 1 2 3 4 5]
