In [2]:
import numpy as np
#creating array using list
arr1=[[1,2,3],[4,5,6],[7,8,9]]
#converting array into numpy array
arr2=np.array(arr1)
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [3]:
#numpy array allow us to apply vectorised opperations 
print(arr2*2)
print(arr2+arr2)
print(arr2*arr2)
print(arr2/4)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[0.25 0.5  0.75]
 [1.   1.25 1.5 ]
 [1.75 2.   2.25]]


In [4]:
#arrays from scratch using numpy
print(np.zeros(100,dtype=int))#creating numpy array filled with zeros 
print(np.ones((3,3),dtype=int))#creating 2d array filled with 1
print(np.arange(0,50,4))#creating an array filled with linear sequence starting from 0 and end 50 with stepsize 4
print(np.linspace(0,1,100))#creating an array of size 100 filled with 0 and 1
print(np.random.randint(0,10,(3,3)))
x=np.random.randint(0,10,(3,3))
print("x dimension=",x.ndim)
print("x Shape=",x.shape)
print("x size=",x.size)
print("x dtype=",x.dtype)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[ 0  4  8 12 16 20 24 28 32 36 40 44 48]
[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.

In [5]:
#array indexing 
#how to access single element in the 1d 2d or nd arrays and how can we change the values of the tuples
x1=np.array([1,2,3,4,6])
#access elements from the start
print(x1[2])
#access elements from the last
print(x1[-1])

3
6


In [6]:
#for 2d array
x2=np.array([[1,2,3],[4,5,6],[7,8,9]])
#accessing elements using row and column values
print(x2[0,2])
print(x2[1,-1])
x2[1,-1]=10
print(x2[1,-1])

3
6
10


In [7]:
#array slicing
x1=np.arange(10)
x2=x1[:5]
x3=x1[::2]
x4=x1[0::3]
print(x1)
print(x2)
print(x3)
print(x4)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[0 2 4 6 8]
[0 3 6 9]


In [8]:
#applying array slicing in 2 dimensional
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2[::-1,::-1])
print(a2[::-1,::])

[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [9]:
#splitting and concatenation of the arrays
#concatenation 
x=np.arange(1,10)
y=np.arange(11,20)
concatenate=np.concatenate([x,y])
print(concatenate)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


In [15]:
z=np.array([[12,14,16],[24,26,28]])
s=np.array([1,2,3])
t=np.array([34,36,38])
print(np.vstack([s,t,z]))

[[ 1  2  3]
 [34 36 38]
 [12 14 16]
 [24 26 28]]


In [16]:
#concatenation of two different dimension of array using hstack and vstack
a=np.array([[1,23,23],[21,213,24]])
b=np.array([[12,14,16],[42,45,47]])
print(np.hstack([a,b]))

[[  1  23  23  12  14  16]
 [ 21 213  24  42  45  47]]


In [21]:
#splitting of array using numpy hsplit and vsplit
grid=np.arange(16).reshape((4,4))
upper,lower=np.vsplit(grid,[2])
print(upper)
print(lower)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [22]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
